name: Call Build and Test workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  call-build-and-test:
    uses: SEG4910CapstoneProject/workflows/.github/workflows/build.yml@main
